# Generated by Django 5.2.4 on 2025-12-26 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikon', models.CharField(help_text='Örn: fa-wifi, fa-swimming-pool (FontAwesome ikon adı)', max_length=50)),
                ('baslik', models.CharField(max_length=100, verbose_name='Hizmet Adı')),
                ('ucretli_mi', models.BooleanField(default=False, verbose_name='Ücretli mi?')),
            ],
            options={
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('tc_no', models.CharField(max_length=11, unique=True)),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OdaTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=50, verbose_name='Oda Türü')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gecelik Fiyat')),
                ('kapasite', models.PositiveIntegerField(default=1, verbose_name='Oda Kapasitesi (Kişi)')),
                ('toplam_oda_sayisi', models.PositiveIntegerField(default=0, verbose_name='Toplam Oda Sayısı')),
                ('kalan_oda_sayisi', models.IntegerField(default=0, verbose_name='Kalan Boş Oda')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='oda_tipleri/')),
                ('hizmetler', models.ManyToManyField(blank=True, to='otelKayit.hizmet', verbose_name='Oda Özellikleri')),
            ],
        ),
        migrations.CreateModel(
            name='Oda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oda_no', models.CharField(max_length=10, unique=True)),
                ('musait_mi', models.BooleanField(default=True)),
                ('ozel_resim', models.ImageField(blank=True, null=True, upload_to='odalar/')),
                ('oda_tipi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otelKayit.odatipi')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giris_tarihi', models.DateField()),
                ('cikis_tarihi', models.DateField()),
                ('kişi_Sayisi', models.PositiveIntegerField(default=1)),
                ('toplam_ucret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('konaklayanlar', models.ManyToManyField(related_name='konaklamalar', to='otelKayit.musteri')),
                ('oda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otelKayit.oda')),
                ('rezervasyonu_yapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yapilan_rezervasyonlar', to='otelKayit.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odeme_yontemi', models.CharField(choices=[('nakit', 'Nakit'), ('kart', 'Kredi Kartı'), ('havale', 'Havale/EFT')], default='nakit', max_length=20)),
                ('odendi_mi', models.BooleanField(default=False)),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True)),
                ('rezervasyon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odeme_detayi', to='otelKayit.rezervasyon')),
            ],
        ),
    ]
