# Generated by Django 5.2.4 on 2025-12-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otelKayit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odatipi',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Oda Açıklaması'),
        ),
    ]
